/***********************************************************************
 * @file      timers.c
 * @version   1.0
 * @brief     Header file for IRQ configuration.
 *
 * @author    Lokesh Senthil Kumar, lokesh.senthilkumar@colorado.edu
 * @date      30-01-2025
 *
 * @institution University of Colorado Boulder (UCB)
 * @course      ECEN 5823: IoT Embedded Firmware
 * @instructor  Chris Choi
 *
 *
 * @resources  Utilized Silicon Labs' Peripheral Libraries (em_letimer.h)
 *             and Course slides
 *
 ***********************************************************************/



#ifndef IRQ_H
#define IRQ_H

// ---------------------------------------------------------------------
// Macro Definitions
// ---------------------------------------------------------------------

/** @brief Macro to convert microseconds to LETIMER ticks. */
#define Micro_TO_TICKS(ms, clk)  (((ms) * (clk)) / 1000)

// ---------------------------------------------------------------------
// Function Declarations
// ---------------------------------------------------------------------

/**
 * @brief Interrupt handler for LETIMER0 events.
 *
 * This function handles interrupts generated by LETIMER0, specifically:
 * - **Underflow (UF)**: Sets the **EVENT_UF** for scheduler processing.
 * - **Compare Match 1 (COMP1)**: Sets the **EVENT_COMP1** and disables further COMP1 interrupts.
 */
void LETIMER0_IRQHandler(void);

/**
 * @brief Returns the total elapsed time in milliseconds.
 *
 * This function calculates the elapsed time by combining the millisecond counter
 * with the number of milliseconds since the last LETIMER underflow.
 *
 * @return Total elapsed time in milliseconds.
 */
uint32_t letimerMilliseconds(void);


#endif // IRQ_H
